language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: master